// @flow
export const NEW_MESSAGE = 'NEW_MESSAGE';
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const UPDATE_CHAT_CHANNEL = 'UPDATE_CHAT_CHANNEL';
export const UPDATE_USERS = 'UPDATE_USERS';
export const UPDATE_CHANNELS = 'UPDATE_CHANNELS';
export const CONNECT = 'CONNECT';
