// @flow

export const NEW_MESSAGE = 'NEW_MESSAGE';
export const UPDATE_CHANNELS = 'UPDATE_CHANNELS';
export const LOGOUT = 'LOGOUT';
export const TWILIO_INVALID = 'TWILIO_INVALID';

export const TCREATE_CHANNEL = 'TWILIO/CREATE_CHANNEL';

export const TCONERROR = 'TWILIO/CONNECTION_ERROR';
export const STOKENERROR = 'SERVER/TOKEN_ERROR';
export const TCONNECTED = 'TWILIO/CONECTED';
export const TCONSTATE = 'TWILIO/CONNECTION_STATE';
export const TUPDATETOKEN = 'TWILIO/UPDATE_TOKEN';
export const TCHANADDED = 'TWILIO/CHANNEL_ADDED';
