// @flow

export const NEW_MESSAGE = 'NEW_MESSAGE';
export const UPDATE_CHANNELS = 'UPDATE_CHANNELS';
export const LOGOUT = 'LOGOUT';
export const TWILIO_INVALID = 'TWILIO_INVALID';

export const TCONNECT = 'TWILIO/CONNECT';
export const TCREATE_CHANNEL = 'TWILIO/CREATE_CHANNEL';
export const TGET_CHANNELS = 'TWILIO/GET_CHANNELS';
